### ISSUE TITLE
OBJ Loader problem

### ISSUE THREAD

**Issue by neondeex** [Bug1312/Bugins#2]
![image](https://github.com/Bug1312/Bugins/assets/30392593/9dc3cce3-7694-4239-ae7d-0c072d14db42)
Here is the function

![image](https://github.com/Bug1312/Bugins/assets/30392593/fc3ca4bf-2629-49c8-bd3e-226e6ff294d6)
Here is where i load it

and here is the error
![image](https://github.com/Bug1312/Bugins/assets/30392593/da2b45b7-6525-4aeb-90ad-13dae05f9583)

Sorry i was unable to find any other way to contact you

**Comment by Bug1312** [comment]
Perfectly fine to contact about my plugins here.

First question before I look into it - Are you running Blockbench 4 or above? Currently we're on 4.7.2 which might I add has native support for OBJ files and is much better of an implementation.
